<?php

namespace Database\Seeders;

use App\Models\Template;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            [
                'name' => 'Hyve Wellness',
                'slug' => 'hyve-wellness',
                'preview_image' => '/images/templates/hyve-wellness-preview.png',
                'description' => 'The flagship wellness template featuring elegant gold accents, modern typography, and a premium aesthetic perfect for health and wellness businesses.',
                'version' => '1.0.0',
                'framework' => 'nextjs',
                'category' => 'wellness',
                'is_active' => true,
                'is_premium' => false,
                'price' => 0,
                'github_repo' => 'your-org/hyve-wellness-template',
                'github_branch' => 'main',
                'build_command' => 'npm run build',
                'output_directory' => 'out',
                'supported_components' => [
                    'hero',
                    'services-grid',
                    'testimonials',
                    'team-section',
                    'faq',
                    'contact-form',
                    'pricing-table',
                    'about-section',
                    'gallery',
                    'blog-posts',
                ],
                'default_settings' => [
                    'show_hero' => true,
                    'show_services' => true,
                    'show_team' => true,
                    'show_testimonials' => true,
                    'show_faq' => true,
                    'show_contact' => true,
                    'hero_style' => 'fullscreen',
                    'services_layout' => 'grid',
                ],
                'default_colors' => [
                    'primary' => '#c9a962',
                    'secondary' => '#3d3d3d',
                    'background' => '#f5f2eb',
                    'text' => '#333333',
                    'accent' => '#8b7355',
                ],
            ],
            [
                'name' => 'Modern Medical',
                'slug' => 'modern-medical',
                'preview_image' => '/images/templates/modern-medical-preview.png',
                'description' => 'A clean, professional template designed for medical practices, clinics, and healthcare providers. Features calming blues and greens with accessible typography.',
                'version' => '1.0.0',
                'framework' => 'nextjs',
                'category' => 'health',
                'is_active' => true,
                'is_premium' => true,
                'price' => 99,
                'github_repo' => 'your-org/modern-medical-template',
                'github_branch' => 'main',
                'build_command' => 'npm run build',
                'output_directory' => 'out',
                'supported_components' => [
                    'hero',
                    'services-grid',
                    'testimonials',
                    'team-section',
                    'faq',
                    'contact-form',
                    'appointment-booking',
                    'location-map',
                ],
                'default_settings' => [
                    'show_hero' => true,
                    'show_services' => true,
                    'show_team' => true,
                    'show_testimonials' => true,
                    'show_appointments' => true,
                    'hero_style' => 'split',
                    'services_layout' => 'list',
                ],
                'default_colors' => [
                    'primary' => '#0077b6',
                    'secondary' => '#023e8a',
                    'background' => '#f8f9fa',
                    'text' => '#212529',
                    'accent' => '#48cae4',
                ],
            ],
            [
                'name' => 'Minimalist Spa',
                'slug' => 'minimalist-spa',
                'preview_image' => '/images/templates/minimalist-spa-preview.png',
                'description' => 'A serene, minimalist template perfect for spas, retreats, and relaxation-focused businesses. Features soft colors and ample white space.',
                'version' => '1.0.0',
                'framework' => 'nextjs',
                'category' => 'wellness',
                'is_active' => true,
                'is_premium' => false,
                'price' => 0,
                'github_repo' => 'your-org/minimalist-spa-template',
                'github_branch' => 'main',
                'build_command' => 'npm run build',
                'output_directory' => 'out',
                'supported_components' => [
                    'hero',
                    'services-grid',
                    'testimonials',
                    'gallery',
                    'pricing-table',
                    'booking-widget',
                ],
                'default_settings' => [
                    'show_hero' => true,
                    'show_services' => true,
                    'show_gallery' => true,
                    'show_testimonials' => true,
                    'show_pricing' => true,
                    'hero_style' => 'minimal',
                    'services_layout' => 'cards',
                ],
                'default_colors' => [
                    'primary' => '#a8dadc',
                    'secondary' => '#457b9d',
                    'background' => '#f1faee',
                    'text' => '#1d3557',
                    'accent' => '#e63946',
                ],
            ],
            [
                'name' => 'Dental Care',
                'slug' => 'dental-care',
                'preview_image' => '/images/templates/dental-care-preview.png',
                'description' => 'A modern dental practice template with appointment booking, service showcase, and team profiles.',
                'version' => '1.0.0',
                'framework' => 'nextjs',
                'category' => 'health',
                'is_active' => true,
                'is_premium' => true,
                'price' => 79,
                'github_repo' => 'your-org/dental-care-template',
                'github_branch' => 'main',
                'build_command' => 'npm run build',
                'output_directory' => 'out',
                'supported_components' => [
                    'hero',
                    'services-grid',
                    'testimonials',
                    'team-section',
                    'faq',
                    'contact-form',
                    'pricing-table',
                    'gallery',
                ],
                'default_settings' => [
                    'show_hero' => true,
                    'show_services' => true,
                    'show_team' => true,
                    'show_testimonials' => true,
                    'show_pricing' => true,
                    'hero_style' => 'centered',
                    'services_layout' => 'cards',
                ],
                'default_colors' => [
                    'primary' => '#2ec4b6',
                    'secondary' => '#011627',
                    'background' => '#ffffff',
                    'text' => '#333333',
                    'accent' => '#ff9f1c',
                ],
            ],
            [
                'name' => 'Fitness Pro',
                'slug' => 'fitness-pro',
                'preview_image' => '/images/templates/fitness-pro-preview.png',
                'description' => 'Dynamic fitness and gym template with class schedules, trainer profiles, and membership options.',
                'version' => '1.0.0',
                'framework' => 'nextjs',
                'category' => 'fitness',
                'is_active' => true,
                'is_premium' => false,
                'price' => 0,
                'github_repo' => 'your-org/fitness-pro-template',
                'github_branch' => 'main',
                'build_command' => 'npm run build',
                'output_directory' => 'out',
                'supported_components' => [
                    'hero',
                    'services-grid',
                    'testimonials',
                    'team-section',
                    'faq',
                    'contact-form',
                    'pricing-table',
                    'schedule',
                    'gallery',
                ],
                'default_settings' => [
                    'show_hero' => true,
                    'show_services' => true,
                    'show_team' => true,
                    'show_schedule' => true,
                    'show_pricing' => true,
                    'hero_style' => 'video',
                    'services_layout' => 'grid',
                ],
                'default_colors' => [
                    'primary' => '#e63946',
                    'secondary' => '#1d3557',
                    'background' => '#f1faee',
                    'text' => '#1d3557',
                    'accent' => '#457b9d',
                ],
            ],
        ];

        foreach ($templates as $template) {
            Template::updateOrCreate(
                ['slug' => $template['slug']],
                $template
            );
        }

        $this->command->info('Templates seeded successfully!');
    }
}
